/**
 * Cleans HTML content by removing empty list items and paragraphs
 * that are commonly generated by rich text editors like TipTap
 */
export function hasTextContent(html: string | null | undefined): boolean {
  if (!html) return false;
  const text = html.replace(/<[^>]*>/g, '').replace(/&nbsp;/gi, ' ').trim();
  return text.length > 0;
}

export function cleanHtmlContent(html: string): string {
  if (!html) return '';
  
  let cleaned = html;
  
  // Handle empty list items with various empty paragraph patterns
  // Order matters - handle more specific patterns first
  cleaned = cleaned.replace(/<li>\s*<p>\s*<br\s*\/?>\s*<\/p>\s*<\/li>/gi, '');
  cleaned = cleaned.replace(/<li>\s*<p>(&nbsp;|\s)*<\/p>\s*<\/li>/gi, '');
  cleaned = cleaned.replace(/<li>\s*<p>\s*<\/p>\s*<\/li>/gi, '');
  cleaned = cleaned.replace(/<li><p><\/p><\/li>/gi, ''); // Exact match, no whitespace
  
  // Remove empty list items: <li></li> or <li> </li> or with &nbsp;
  cleaned = cleaned.replace(/<li>(\s|&nbsp;)*<\/li>/gi, '');
  
  // Remove standalone empty paragraphs: <p></p> or <p> </p> or <p><br></p>
  cleaned = cleaned.replace(/<p>\s*<\/p>/gi, '');
  cleaned = cleaned.replace(/<p>\s*<br\s*\/?>\s*<\/p>/gi, '');
  
  // Remove paragraphs with only &nbsp;
  cleaned = cleaned.replace(/<p>(&nbsp;|\s)+<\/p>/gi, '');
  
  // Clean up multiple consecutive <br> tags
  cleaned = cleaned.replace(/(<br\s*\/?>\s*){2,}/gi, '<br>');
  
  // Remove empty unordered lists that might result from cleaning
  cleaned = cleaned.replace(/<ul>\s*<\/ul>/gi, '');
  
  return cleaned.trim();
}

/**
 * Converts all content to a unified bullet list format
 * Extracts content from existing lists AND paragraphs, then rebuilds as single list
 * Used for announcement cards on the dashboard
 */
export function convertToBulletList(htmlContent: string): string {
  if (!htmlContent) return '';
  
  // First clean the content
  let cleaned = cleanHtmlContent(htmlContent);
  
  // Extract ALL text content regardless of existing structure
  // This ensures mixed content (ul + p) becomes unified bullets
  
  // 1. Extract text from existing list items (handle nested <p> tags)
  const listItemMatches = cleaned.match(/<li>.*?<\/li>/gis) || [];
  const listTexts = listItemMatches
    .map(li => {
      // Remove li and p tags, preserve inner content
      let text = li.replace(/<\/?li>/gi, '').replace(/<\/?p>/gi, '').trim();
      // Clean up any remaining br tags
      text = text.replace(/<br\s*\/?>/gi, '').trim();
      return text;
    })
    .filter(text => {
      const stripped = text.replace(/&nbsp;/gi, '').trim();
      return stripped.length > 0;
    });
  
  // 2. Remove existing ul structure to get remaining paragraphs
  let remaining = cleaned.replace(/<ul>.*?<\/ul>/gis, '');
  
  // 3. Extract text from remaining paragraphs
  const paragraphs = remaining
    .split(/<\/?p>/gi)
    .map(p => p.replace(/<br\s*\/?>/gi, '').trim())
    .filter(p => {
      const stripped = p.replace(/&nbsp;/gi, '').trim();
      return stripped.length > 0;
    });
  
  // 4. Combine all items (list items first, then paragraphs)
  const allItems = [...listTexts, ...paragraphs];
  
  if (allItems.length === 0) return '';
  
  // 5. Build unified bullet list
  const listItems = allItems.map(item => `<li>${item}</li>`).join('');
  return `<ul>${listItems}</ul>`;
}
