/**
 * HTML Report Viewer Utility
 * Handles cross-platform HTML report viewing with mobile-first approach
 */

import { isMobile, isPWA } from './mobile-detection';

/**
 * Format report type for display
 */
function formatReportType(reportType: string): string {
  switch (reportType) {
    case 'inspection':
      return 'Inspection';
    case 'training':
      return 'Training';
    case 'daily_assessment':
      return 'Daily Assessment';
    default:
      return reportType.charAt(0).toUpperCase() + reportType.slice(1);
  }
}

/**
 * Generate SMS link with pre-filled report metadata
 */
export function generateSmsLink(
  reportType: string,
  organization: string,
  date: string
): string {
  const message = [
    `${formatReportType(reportType)} Report`,
    `Organization: ${organization}`,
    `Date: ${date}`,
    `Generated by Rope Works Inspection System`
  ].join('\n');
  
  return `sms:?body=${encodeURIComponent(message)}`;
}

/**
 * Check if SMS sharing should be available (mobile only)
 */
export function canShareViaSms(): boolean {
  return isMobile() || isPWA();
}

export interface ViewerOptions {
  html: string;
  filename: string;
  title: string;
}

/**
 * Open HTML report with appropriate method based on platform
 * Returns true if viewer was opened successfully, false otherwise
 */
export function openHtmlReport(options: ViewerOptions): boolean {
  const { html, filename, title } = options;
  
  // On mobile/PWA: always use in-app viewer (will be handled by React component)
  // This function just returns false to indicate React component should handle it
  if (isMobile() || isPWA()) {
    return false; // Signal to use React component
  }

  // On desktop: try window.open with fallback
  try {
    const newWindow = window.open('', '_blank');
    
    if (!newWindow) {
      // Popup blocked - signal to use React component
      return false;
    }

    // Write HTML content to new window
    newWindow.document.open();
    newWindow.document.write(html);
    newWindow.document.close();
    
    // Set title
    if (newWindow.document.title) {
      newWindow.document.title = title;
    }

    return true;
  } catch (error) {
    console.error('[HTMLViewer] Failed to open in new window:', error);
    return false;
  }
}

/**
 * Download HTML report as a file
 */
export function downloadHtmlReport(html: string, _filename: string): void {
  try {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      console.error('[HTMLViewer] Popup blocked - cannot open print window');
      return;
    }

    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();

    // Wait for content (images/fonts) to load, then trigger print
    const triggerPrint = () => {
      try {
        printWindow.focus();
        printWindow.print();
      } catch (e) {
        console.error('[HTMLViewer] Print failed:', e);
      }
    };

    // Use onload to wait for images, with a fallback timeout
    if (printWindow.document.readyState === 'complete') {
      setTimeout(triggerPrint, 300);
    } else {
      printWindow.onload = () => setTimeout(triggerPrint, 300);
      // Fallback if onload never fires
      setTimeout(triggerPrint, 3000);
    }
  } catch (error) {
    console.error('[HTMLViewer] Failed to open print dialog:', error);
  }
}

/**
 * Check if Web Share API is available and can share HTML files
 */
export function canShareHtml(): boolean {
  return 'share' in navigator && 'canShare' in navigator;
}

/**
 * Share HTML report using Web Share API (mobile)
 */
/**
 * Print directly from an existing iframe element (fallback for mobile)
 */
export function printFromIframe(iframe: HTMLIFrameElement): boolean {
  try {
    const contentWindow = iframe.contentWindow;
    if (!contentWindow) {
      console.error('[HTMLViewer] No contentWindow on iframe');
      return false;
    }
    contentWindow.focus();
    contentWindow.print();
    return true;
  } catch (error) {
    console.error('[HTMLViewer] Failed to print from iframe:', error);
    return false;
  }
}

export async function shareHtmlReport(html: string, filename: string, title: string): Promise<boolean> {
  if (!canShareHtml()) {
    return false;
  }

  try {
    const blob = new Blob([html], { type: 'text/html' });
    const file = new File([blob], filename, { type: 'text/html' });
    
    const shareData = {
      title,
      files: [file],
    };

    if (navigator.canShare && !navigator.canShare(shareData)) {
      return false;
    }

    await navigator.share(shareData);
    return true;
  } catch (error) {
    if ((error as Error).name !== 'AbortError') {
      console.error('[HTMLViewer] Failed to share:', error);
    }
    return false;
  }
}
