/**
 * Cleans HTML content by removing empty list items and paragraphs
 * that are commonly generated by rich text editors
 */
export function cleanHtmlContent(html: string): string {
  if (!html) return '';
  
  let cleaned = html;
  
  // Remove empty paragraphs inside list items: <li><p></p></li> or <li><p> </p></li>
  cleaned = cleaned.replace(/<li>\s*<p>\s*<\/p>\s*<\/li>/gi, '');
  
  // Remove empty list items: <li></li> or <li> </li>
  cleaned = cleaned.replace(/<li>\s*<\/li>/gi, '');
  
  // Remove standalone empty paragraphs: <p></p> or <p> </p> or <p><br></p>
  cleaned = cleaned.replace(/<p>\s*<\/p>/gi, '');
  cleaned = cleaned.replace(/<p>\s*<br\s*\/?>\s*<\/p>/gi, '');
  
  // Remove paragraphs with only &nbsp;
  cleaned = cleaned.replace(/<p>(&nbsp;|\s)+<\/p>/gi, '');
  
  // Clean up multiple consecutive <br> tags
  cleaned = cleaned.replace(/(<br\s*\/?>\s*){2,}/gi, '<br>');
  
  // Remove empty unordered lists that might result from cleaning
  cleaned = cleaned.replace(/<ul>\s*<\/ul>/gi, '');
  
  return cleaned.trim();
}

/**
 * Converts paragraph-based content to bullet list format
 * Used for announcement cards on the dashboard
 */
export function convertToBulletList(htmlContent: string): string {
  if (!htmlContent) return '';
  
  // First clean the content
  let cleaned = cleanHtmlContent(htmlContent);
  
  // If already has bullet list, just return cleaned version
  if (cleaned.includes('<ul>') || cleaned.includes('<li>')) {
    return cleaned;
  }
  
  // Extract text from paragraphs
  const paragraphs = cleaned
    .split(/<\/?p>/gi)
    .map(p => p.trim())
    .filter(p => {
      // Filter out empty, whitespace-only, or just <br> tags
      const stripped = p.replace(/<br\s*\/?>/gi, '').replace(/&nbsp;/gi, '').trim();
      return stripped.length > 0;
    });
  
  if (paragraphs.length === 0) return '';
  
  // Convert to bullet list
  const listItems = paragraphs.map(p => `<li>${p}</li>`).join('');
  return `<ul>${listItems}</ul>`;
}
