project_id = "ssgzcgvygnsrqalisshx"

[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.generate-inspection-pdf]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false