project_id = "ssgzcgvygnsrqalisshx"

[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.check-overdue-reports]
verify_jwt = false

[functions.generate-inspection-pdf]
verify_jwt = true

[functions.generate-inspection-html]
verify_jwt = true

[functions.generate-training-pdf]
verify_jwt = true

[functions.generate-training-html]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-training-pdf-email]
verify_jwt = true

[functions.get-logo-base64]
verify_jwt = false

[functions.extract-names]
verify_jwt = true

[functions.migrate-field-history]
verify_jwt = true
 
 [functions.send-report-email]
 verify_jwt = true
