import "@testing-library/jest-dom";
// fake-indexeddb auto-installs window.indexedDB / IDBKeyRange polyfills so
// boundary tests (H6) can exercise getUnsynced* against a real IDB.
import "fake-indexeddb/auto";

// vitest's jsdom env tears down `window.localStorage` after each test
// file. vite-node may then lazily evaluate
// `src/integrations/supabase/client.ts` during the inter-file gap — that
// auto-generated module references bare `localStorage` at module top
// level, surfacing as an unhandled
// `ReferenceError: localStorage is not defined`. The Supabase client
// module is regenerated by tooling and a guard added there gets reverted
// (see commits cfd8972a and 702da11e), so the durable fix is here in the
// shared test setup.
//
// Install a `globalThis.localStorage` shim that survives jsdom teardown:
// when jsdom's window.localStorage is alive we proxy to it, otherwise we
// fall back to an in-memory Map. This is invisible to tests that read or
// write `localStorage` because the shim transparently delegates to
// jsdom's real storage during the test run.
{
  const memoryStore = new Map<string, string>();
  const memoryShim: Storage = {
    get length() { return memoryStore.size; },
    key(i: number) { return Array.from(memoryStore.keys())[i] ?? null; },
    getItem(k: string) { return memoryStore.has(k) ? memoryStore.get(k)! : null; },
    setItem(k: string, v: string) { memoryStore.set(k, String(v)); },
    removeItem(k: string) { memoryStore.delete(k); },
    clear() { memoryStore.clear(); },
  };

  const previousDescriptor = Object.getOwnPropertyDescriptor(globalThis, "localStorage");

  Object.defineProperty(globalThis, "localStorage", {
    configurable: true,
    enumerable: true,
    get(): Storage {
      // Prefer jsdom's storage when the window object is still alive —
      // tests that exercise real localStorage semantics keep working.
      if (previousDescriptor?.get) {
        try {
          const real = previousDescriptor.get.call(globalThis) as Storage | undefined;
          if (real) return real;
        } catch { /* jsdom torn down — fall through to memory shim */ }
      } else if (previousDescriptor && "value" in previousDescriptor) {
        const real = previousDescriptor.value as Storage | undefined | null;
        if (real != null) {
          try {
            // Cheap liveness probe: accessing length on a torn-down
            // jsdom Storage throws.
            void real.length;
            return real;
          } catch { /* fall through */ }
        }
      }
      return memoryShim;
    },
    set(v: Storage) {
      Object.defineProperty(globalThis, "localStorage", {
        configurable: true,
        enumerable: true,
        writable: true,
        value: v,
      });
    },
  });
}

Object.defineProperty(window, "matchMedia", {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => {},
  }),
});
