// Single source of truth for which tables get backed up / restored.
// Order matters for restore: parents before children.
export const BACKUP_TABLES = [
  "organizations",
  "profiles",
  "organization_members",
  "user_roles",
  "admin_settings",
  "app_announcements",
  "notification_preferences",
  "push_subscriptions",
  "form_sections",
  "form_fields",
  "form_field_options",
  "form_translations",
  "form_versions",
  "global_field_history",
  "user_field_history",
  "onboarding_resources",
  "onboarding_progress",
  "inspections",
  "inspection_systems",
  "inspection_equipment",
  "inspection_standards",
  "inspection_photos",
  "inspection_ziplines",
  "inspection_summary",
  "inspection_reports",
  "trainings",
  "training_systems",
  "training_equipment",
  "training_photos",
  "training_operating_systems",
  "training_delivery_approaches",
  "training_verifiable_items",
  "training_immediate_attention",
  "training_systems_in_place",
  "training_summary",
  "training_reports",
  "daily_assessments",
  "daily_assessment_beginning_of_day",
  "daily_assessment_end_of_day",
  "daily_assessment_environment_checks",
  "daily_assessment_equipment_checks",
  "daily_assessment_operating_systems",
  "daily_assessment_structure_checks",
  "daily_assessment_photos",
  "jcf_reports",
  "jcf_photos",
  "audit_logs",
] as const;

export type BackupTable = typeof BACKUP_TABLES[number];
