// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { retryingFetch } from './retrying-fetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// `localStorage` is referenced lazily so that this module can be imported
// in non-browser execution contexts (vitest's vite-node module-graph
// evaluation between jsdom test files; SSR; build-time analysis) without
// triggering `ReferenceError: localStorage is not defined`. In the
// browser, Supabase's auth module reads `auth.storage` synchronously
// during the first session call, which always happens after the DOM
// is ready, so the runtime behaviour is unchanged.
const browserLocalStorage =
  typeof globalThis !== 'undefined' && 'localStorage' in globalThis
    ? (globalThis as { localStorage?: Storage }).localStorage
    : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: browserLocalStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Retry idempotent requests on `TypeError: Failed to fetch` so transient
  // network blips (CI runner instability, real-user cellular handoffs)
  // don't surface as user-facing errors. See `retrying-fetch.ts` for the
  // safety contract — only GET/HEAD/OPTIONS are retried; mutations are
  // handled by higher-level retry/queue layers.
  global: {
    fetch: retryingFetch,
  },
});